IF(NOT APPLE)
    RETURN()
ENDIF()

IF($ENV{PATH} MATCHES "(^|:)/usr/local/bin/?(:|$)")
    SET(MAC_HOMEBREW ON)
ELSE()
    SET(CMAKE_IGNORE_PATH /usr/local /usr/local/bin /usr/local/include /usr/local/Frameworks /usr/local/lib ${CMAKE_IGNORE_PATH})
ENDIF()
IF($ENV{PATH} MATCHES "(^|:)/opt/local/bin/?(:|$)")
    SET(MACPORTS ON)
ELSE()
    SET(CMAKE_IGNORE_PATH /opt/local /opt/local/bin /opt/local/include /opt/local/Library/Frameworks /opt/local/lib ${CMAKE_IGNORE_PATH})
ENDIF()
IF($ENV{PATH} MATCHES "(^|:)/sw/bin/?(:|$)")
    SET(FINK ON)
ELSE()
    SET(CMAKE_IGNORE_PATH /sw /sw/bin /sw/include /sw/Library/Frameworks /sw/lib ${CMAKE_IGNORE_PATH})
ENDIF()

IF(MACPORTS AND EXISTS /opt/local/Library/Frameworks)
    SET(CMAKE_FRAMEWORK_PATH /opt/local/Library/Frameworks ${CMAKE_FRAMEWORK_PATH})
ENDIF()
IF(FINK AND EXISTS /sw/Library/Frameworks)
    SET(CMAKE_FRAMEWORK_PATH /sw/Library/Frameworks ${CMAKE_FRAMEWORK_PATH})
ENDIF()
IF(MAC_HOMEBREW AND EXISTS /usr/local/Frameworks)
    SET(CMAKE_FRAMEWORK_PATH /usr/local/Frameworks ${CMAKE_FRAMEWORK_PATH})
ENDIF()

IF(MACPORTS AND EXISTS /opt/local/include)
    SET(CMAKE_INCLUDE_PATH /opt/local/include ${CMAKE_INCLUDE_PATH})
    INCLUDE_DIRECTORIES("/opt/local/include")
ENDIF()
IF(FINK AND EXISTS /sw/include)
    SET(CMAKE_INCLUDE_PATH /sw/include ${CMAKE_INCLUDE_PATH})
    INCLUDE_DIRECTORIES("/sw/include")
ENDIF()
IF(MAC_HOMEBREW AND EXISTS /usr/local/include)
    SET(CMAKE_INCLUDE_PATH /usr/local/include ${CMAKE_INCLUDE_PATH})
    INCLUDE_DIRECTORIES("/usr/local/include")
ENDIF()

IF(MACPORTS AND EXISTS /opt/local/lib)
    SET(CMAKE_LIBRARY_PATH /opt/local/lib ${CMAKE_LIBRARY_PATH})
    LINK_DIRECTORIES("/opt/local/lib")
ENDIF()
IF(FINK AND EXISTS /sw/lib)
    SET(CMAKE_LIBRARY_PATH /sw/lib ${CMAKE_LIBRARY_PATH})
    LINK_DIRECTORIES("/sw/lib")
ENDIF()
IF(MAC_HOMEBREW AND EXISTS /usr/local/lib)
    SET(CMAKE_LIBRARY_PATH /usr/local/lib ${CMAKE_LIBRARY_PATH})
    LINK_DIRECTORIES("/usr/local/lib")
ENDIF()

IF(MACPORTS AND EXISTS /opt/local/bin)
    SET(CMAKE_PROGRAM_PATH /opt/local/bin ${CMAKE_PROGRAM_PATH})
    IF(EXISTS "/opt/local/bin/nasm")
        SET(CMAKE_ASM_NASM_COMPILER "/opt/local/bin/nasm")
    ENDIF()
ENDIF()
IF(FINK AND EXISTS /sw/bin)
    SET(CMAKE_PROGRAM_PATH /sw/bin ${CMAKE_PROGRAM_PATH})
    IF(EXISTS "/sw/bin/nasm")
        SET(CMAKE_ASM_NASM_COMPILER "/sw/bin/nasm")
    ENDIF()
ENDIF()
IF(MAC_HOMEBREW AND EXISTS /usr/local/bin)
    SET(CMAKE_PROGRAM_PATH /usr/local/bin ${CMAKE_PROGRAM_PATH})
    IF(EXISTS "/usr/local/bin/nasm")
        SET(CMAKE_ASM_NASM_COMPILER "/usr/local/bin/nasm")
    ENDIF()
ENDIF()
